-- Membuat tabel untuk menyimpan percakapan antara dua pengguna
CREATE TABLE public.conversations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    -- Menyimpan ID dari kedua profil yang terlibat dalam percakapan
    participant_ids UUID[] NOT NULL
);

-- Membuat tabel untuk menyimpan setiap pesan
CREATE TABLE public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    content TEXT NOT NULL,
    -- Menghubungkan pesan ke percakapan
    conversation_id UUID REFERENCES public.conversations(id) ON DELETE CASCADE NOT NULL,
    -- Menghubungkan pesan ke pengirim
    sender_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL
);

-- Mengaktifkan Realtime untuk tabel messages agar chat bisa live
ALTER PUBLICATION supabase_realtime ADD TABLE public.messages;

-- Mengaktifkan RLS untuk kedua tabel
ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- Kebijakan: Pengguna hanya bisa melihat/membuat percakapan yang melibatkan diri mereka sendiri
CREATE POLICY "Users can access their own conversations"
ON public.conversations
USING (
  (SELECT id FROM public.profiles WHERE user_id = auth.uid()) = ANY(participant_ids)
);

-- Kebijakan: Pengguna hanya bisa mengakses pesan dalam percakapan yang mereka ikuti
CREATE POLICY "Users can access messages in their conversations"
ON public.messages
USING (
  EXISTS (
    SELECT 1 FROM public.conversations
    WHERE conversations.id = messages.conversation_id
  )
);