-- 1. Membuat tabel untuk notifikasi
CREATE TABLE public.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    message TEXT NOT NULL,
    link TEXT, -- Link untuk navigasi saat notifikasi diklik
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);
COMMENT ON TABLE public.notifications IS 'Stores notifications for users.';

-- 2. Mengaktifkan RLS
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- 3. Kebijakan RLS: Pengguna hanya bisa mengakses notifikasi mereka sendiri
CREATE POLICY "Users can view and manage their own notifications"
ON public.notifications
USING ( auth.uid() = user_id );

-- 4. Mengaktifkan Realtime untuk tabel notifications
ALTER PUBLICATION supabase_realtime ADD TABLE public.notifications;

-- 5. Fungsi untuk membuat notifikasi saat ada PESANAN BARU (untuk MUA)
CREATE OR REPLACE FUNCTION public.handle_new_booking_notification()
RETURNS TRIGGER AS $$
DECLARE
  v_mua_user_id UUID;
  v_customer_name TEXT;
BEGIN
  -- Dapatkan user_id MUA dari profile_id
  SELECT p.user_id INTO v_mua_user_id
  FROM public.mua_profiles mp JOIN public.profiles p ON mp.profile_id = p.id
  WHERE mp.id = NEW.mua_profile_id;

  -- Dapatkan nama pelanggan
  SELECT full_name INTO v_customer_name FROM public.profiles WHERE id = NEW.customer_id;

  -- Buat notifikasi untuk MUA
  INSERT INTO public.notifications (user_id, message, link)
  VALUES (v_mua_user_id, 'Anda memiliki pesanan baru dari ' || v_customer_name || '!', '/mua/profile?tab=dashboard');

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 6. Trigger untuk PESANAN BARU
CREATE TRIGGER on_new_booking_create_notification
AFTER INSERT ON public.bookings
FOR EACH ROW EXECUTE FUNCTION public.handle_new_booking_notification();

-- 7. Fungsi untuk membuat notifikasi saat PESANAN DITERIMA/DITOLAK (untuk Pelanggan)
CREATE OR REPLACE FUNCTION public.handle_booking_status_update_notification()
RETURNS TRIGGER AS $$
DECLARE
  v_customer_user_id UUID;
  v_mua_business_name TEXT;
  v_status_text TEXT;
BEGIN
  -- Hanya berjalan jika status berubah
  IF OLD.status <> NEW.status AND (NEW.status = 'accepted' OR NEW.status = 'rejected') THEN
    -- Dapatkan user_id pelanggan
    SELECT user_id INTO v_customer_user_id FROM public.profiles WHERE id = NEW.customer_id;
    -- Dapatkan nama bisnis MUA
    SELECT business_name INTO v_mua_business_name FROM public.mua_profiles WHERE id = NEW.mua_profile_id;

    IF NEW.status = 'accepted' THEN v_status_text := 'diterima';
    ELSE v_status_text := 'ditolak';
    END IF;

    -- Buat notifikasi untuk Pelanggan
    INSERT INTO public.notifications (user_id, message, link)
    VALUES (v_customer_user_id, 'Pesanan Anda telah ' || v_status_text || ' oleh ' || v_mua_business_name, '/aktivitas');
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 8. Trigger untuk UPDATE STATUS PESANAN
CREATE TRIGGER on_booking_status_update_create_notification
AFTER UPDATE ON public.bookings
FOR EACH ROW EXECUTE FUNCTION public.handle_booking_status_update_notification();