-- Membuat tabel untuk menyimpan slot waktu yang diblokir oleh MUA
CREATE TABLE public.mua_blocked_slots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mua_profile_id UUID NOT NULL REFERENCES public.mua_profiles(id) ON DELETE CASCADE,
    start_time TIMESTAMP WITH TIME ZONE NOT NULL,
    end_time TIMESTAMP WITH TIME ZONE NOT NULL,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Mengaktifkan RLS
ALTER TABLE public.mua_blocked_slots ENABLE ROW LEVEL SECURITY;

-- Menambahkan komentar
COMMENT ON TABLE public.mua_blocked_slots IS 'Stores specific time slots manually blocked by MUAs.';

-- Kebijakan: MUA hanya bisa mengakses dan mengelola slot waktu mereka sendiri
CREATE POLICY "MUAs can manage their own blocked slots"
ON public.mua_blocked_slots
USING (
  EXISTS (
    SELECT 1 FROM public.mua_profiles mp
    JOIN public.profiles p ON mp.profile_id = p.id
    WHERE mp.id = mua_blocked_slots.mua_profile_id AND p.user_id = auth.uid()
  )
);