CREATE TABLE public.favorites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  mua_profile_id UUID NOT NULL REFERENCES public.mua_profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  CONSTRAINT favorites_customer_mua_unique UNIQUE (customer_id, mua_profile_id)
);

ALTER TABLE public.favorites ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own favorites" ON public.favorites FOR SELECT USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = favorites.customer_id AND user_id = auth.uid()));
CREATE POLICY "Users can insert their own favorites" ON public.favorites FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM public.profiles WHERE id = favorites.customer_id AND user_id = auth.uid()));
CREATE POLICY "Users can delete their own favorites" ON public.favorites FOR DELETE USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = favorites.customer_id AND user_id = auth.uid()));