// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvkdnyxcdcxwpdgkijpy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2a2RueXhjZGN4d3BkZ2tpanB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1OTI1NTEsImV4cCI6MjA2NzE2ODU1MX0.OCHT7ZJRgZbIty0kW6n1vxh43MjPTYefalA42jJboXI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});